name: Lider Sale App CI

on:
  push:
    branches: [ stage ]
  pull_request:
    branches: [ stage ]

jobs:

  test:
    name: Test - Units & Integrations
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Setup Java JDK
        uses: actions/setup-java@v1.4.3
        with:
          java-version: 11.0.7 # The JDK version to make available on the path.
      - name: Use Node.js
        uses: actions/setup-node@v1.4.4
        with:
          node-version: '12.x'
      - run : npm install
      - name: Angular Test
        run: npm run testreport
      - name: SonarCloud Scan
        run: npm run sonar
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
