name: Lider Sale App CI

on:
  push:
    branches: [ stage ]
  pull_request:
    branches: [ stage ]

jobs:

  test:
    name: Test - Units & Integrations
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js
        uses: actions/setup-node@v1.4.4
        with:
          node-version: '12.x'
      - run : npm install
      - name: Angular Test
        run: npm run testreport
